version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - elasticsearch

volumes:
  mongo_data:
  elastic_data:
